npm install --save-dev bootstrap bootstrap-material-design@https://github.com/cjsheets/bootstrap-material-design/tarball/dist-cjs 
echo '|--- Sort the package.json'
echo '|'
echo '|'
echo '|--- And add to angular-cli.json:'
echo '|'
echo '"styles": ['
echo '"../node_modules/bootstrap/dist/css/bootstrap.css",'
echo '"../node_modules/bootstrap-material-design/css/bootstrap-material-design.css",'
echo '"../node_modules/bootstrap-material-design/css/ripples.css",'
echo '"scripts": ['
echo '"../node_modules/jquery/dist/jquery.js",'
echo '"../node_modules/bootstrap/dist/js/bootstrap.js"'
echo '|'
echo '|'
